version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kaka_event_pipeline_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: edtech_orders
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper:
    image: "confluentinc/cp-zookeeper:6.2.4"
    container_name: kaka_event_pipeline_zookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: "confluentinc/cp-enterprise-kafka"
    container_name: kaka_event_pipeline_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      # Exposes 9092 for external connections to the broker
      # Use kafka:29092 for connections internal on the docker network
      # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      CONFLUENT_METRICS_ENABLE: 'false'

  akhq:
    container_name: kaka_event_pipeline_kafka-ui-akhq
    image: tchiotludo/akhq
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"
  #              schema-registry:
  #                url: "http://schema-registry:8081"
  #              connect:
  #                - name: "connect"
  #                  url: "http://kafka-connect:8083"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kaka_event_pipeline_kafka-ui-provectuslab
    depends_on:
      - kafka
    ports:
      - "7777:8080"
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

volumes:
  mysql_data: